services:
  ollama:
    platform: linux/arm64
    image: ollama/ollama:latest
    container_name: slm-ollama
    ports: ["11434:11434"]
    volumes:
      - ollama:/root/.ollama

  # Milvus dependencies
  etcd:
    platform: linux/arm64
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
    ports: ["2379:2379"]

  minio:
    platform: linux/arm64
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports: ["9000:9000"]

  milvus:
    platform: linux/arm64
    image: milvusdb/milvus:v2.5.17
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    depends_on: [etcd, minio]
    ports: ["19530:19530"]

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    environment:
      OPENAI_BASE_URL: http://ollama:11434/v1
      OPENAI_API_KEY: dummy
      LLM_MODEL: phi3:mini
      # RAG settings
      MILVUS_HOST: milvus
      MILVUS_PORT: 19530
      MILVUS_COLLECTION: company_kb_v2
      EMBEDDINGS_KIND: local           # local | openai
      EMBEDDINGS_MODEL: sentence-transformers/all-MiniLM-L6-v2  # used if local
      OPENAI_EMBED_MODEL: text-embedding-3-small # used if openai
    depends_on: [ollama, milvus]
    ports: ["8000:8000"]
    volumes:
      - ../data:/data     # host ./data -> container /data

volumes:
  ollama:
